# Generated by Django 5.1.5 on 2025-01-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watering", "0002_remove_wateringstatus_message_wateringstatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="wateringstatus",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wateringstatus",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wateringstatus",
            name="volume",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
