# Generated by Django 5.1.5 on 2025-01-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watering", "0004_wateringstatus_watering_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wateringstatus",
            name="start_time",
        ),
        migrations.AddField(
            model_name="wateringstatus",
            name="postponed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
