# Generated by Django 5.1.5 on 2025-01-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watering", "0005_remove_wateringstatus_start_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wateringstatus",
            name="watering_time",
        ),
    ]
