# Generated by Django 5.1.5 on 2025-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watering", "0006_remove_wateringstatus_watering_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="wateringstatus",
            name="watering_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
