# Generated by Django 5.1.5 on 2025-01-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ventilation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("on", "Включено"), ("off", "Выключено")],
                        default="off",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
