# Generated by Django 5.1.5 on 2025-01-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TempAndHumidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField(default=20)),
                ("humidity", models.IntegerField(default=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Температура и влажность",
                "verbose_name_plural": "Температуры и влажности",
            },
        ),
    ]
