# Generated by Django 5.1.5 on 2025-01-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temp_n_humidity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempandhumidity",
            name="humidity",
            field=models.IntegerField(default=60),
        ),
    ]
